language: ruby

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up
  - docker-compose down
  - docker-compose up
  - docker exec -ti uspmais_web_1 rspec
  - docker exec -ti uspmais_web_1 cucumber

script:
  - rspec
  - cucumber
