language: ruby

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d
  - docker-compose down
  - docker-compose up -d

script:
  - docker exec -ti uspmais_web_1 rspec
# - docker exec -ti uspmais_web_1 cucumber
