version: '3'
services:
  db:
    image: postgres
    volumes:
      - /tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: >
        bash -c "rm -f tmp/pids/server.pid &&
        bundle exec rake db:create &&
        bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/uspmais
    ports:
      - "3000:3000"
    depends_on:
      - db
